### ISSUE TITLE
Any new builds for macOS Big Sur?

### ISSUE THREAD

**Issue by adityashukzy** [lakshayg/tensorflow-build#5]
I have Python 3.7 and macOS Big Sur. When I try to run an OpenCV program, it throws me the FMA AVX2 not present error and tells me to install a build that includes support for them, so I was linked to this repo. However, I have the stable install of the new macOS Big Sur. I tried the 3.7 build for High Sierra but that gave me the Illegal Instruction: 4 error meaning I'm trying to use a program built for an older OS. I haven't as yet tried the one for Catalina because a) it is Python 3.8 and b) because again I expect Illegal Instruction: 4 error.

Any ideas where to go from here if you can provide me with a build for the Big Sur with Python 3.7? I intend to integrate OpenCV with Streamlit so I can't make do with Colab's GPU thing either since I don't think it will be possible to get Streamlit working with Colab.

**Comment by lakshayg** [comment]
I don't think I have a python3.7 build for High Sierra. Is this build from a different source? If so, you should check the instruction sets enabled when compiling that binary.

The "Illegal Instruction: 4" error means that the build is using instruction sets not supported by your processor. To determine what instruction sets are supported by your process, you can use:

```
sysctl -a | grep "machdep.cpu.*features:"
```

If your machine supports AVX, AVX2, FMA, SSE4.1, SSE4.2, I'll add a new build at some point but it will very likely be for python 3.8 since that is the latest version supported by TensorFlow and I do not plan on supporting all possible valid configurations.

You can also try building tensorflow from source by following the instructions at https://www.tensorflow.org/install/source

**Comment by adityashukzy** [comment]
No problem, Lakshay! I installed Anaconda on my system and was able to get rid of that problem. Either way, thanks for your help and quick response! You can close this issue.
